name: "test-publish-CI-CD"

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Check output
        run:
          echo ${{ steps.vars.outputs.tag }}


  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'Building'

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: echo 'Publishing'
        
